name: CalebCompass
version: 3.2
main: calebcompass.calebcompass.CalebCompass
api-version: 1.16
description: CalebCompass
author: CalebBritannia
softdepend:
  - BetonQuest
  - Citizens
  - MythicMobs
  - Towny

commands:
  calebcompass:
    usage: '§e/calebcompass help'
    aliases: [calcomp]
