name: CalebCompass
version: 3.2
main: calebcompass.calebcompass.CalebCompass
api-version: 1.13
description: CalebCompass
softdepend:
  - BetonQuest
  - Citizens
  - MythicMobs

commands:
  calebcompass:
    usage: '§e/calebcompass help'
    aliases: [calcomp]
